services:
  personyx_db:
    restart: unless-stopped
    image: postgres:12
    container_name: personyx-db
    ports:
      - "5211:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../pg12_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  personyx_bot:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: personyx-service/Dockerfile.bot
    container_name: personyx-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PYTHONUNBUFFERED=1
      - WIF_PRIVATE_KEY_PATH=/app/secret/uw_private_key.pem
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - VERTEXAI_PROJECT_ID=${VERTEXAI_PROJECT_ID}
      - VERTEXAI_LOCATION=${VERTEXAI_LOCATION}
    depends_on:
      - personyx_db
    volumes:
      - ../personyx/bot:/app/bot
      - ../gen_images:/app/gen_images
      - ${HOST_KEY_PATH:-~/.ssh/uw_private_key.pem}:/app/secret/uw_private_key.pem:ro
    working_dir: /app/bot

  personyx_web:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: personyx-service/Dockerfile.web
    container_name: personyx-web
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app/web
    depends_on:
      - personyx_db
    volumes:
      - ../personyx/web:/app/web
      - ../alembic.ini:/app/web/alembic.ini
      - ../gen_images:/app/gen_images
    working_dir: /app/web
    command: ["sh", "-c", "alembic upgrade head && python app.py"]
