FROM python:3.11-slim

# アプリディレクトリ作成
WORKDIR /app/web

# 依存パッケージのインストール
COPY personyx/web/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# alembic.ini
COPY ../alembic.ini ./
COPY ../personyx/web/ ./personyx/web/

# ポートlisten
EXPOSE 5000
