-- bot_profile_groups
INSERT INTO personyx.bot_profile_groups (user_id, name, description, is_active)
VALUES
  ('39eff062-1d05-41a0-9777-ca949b445844', 'イラスト', '1980年代のレトロ風イラストに向いたプロファイル', TRUE),
  ('39eff062-1d05-41a0-9777-ca949b445844', '実写', '実写・リアル系の生成スタイルに向いたプロファイル', TRUE);

-- personas
insert into personyx.personas(id,user_id,name,icon_url,persona_config,workflow_id,created_at) values 
    ('{1166e3bb-6824-4dd0-945c-80eec3721810}','{39eff062-1d05-41a0-9777-ca949b445844}','Lotta','https://example.com/lotta.png','{"name": "Lotta", "rating": {"safe": "rating_safe", "explicit": "rating_explicit", "questionable": "rating_questionable"}, "base_style": "source_photo, photorealistic, realistic, RAW photo, 8k uhd, dslr", "body_parts": {"eyes": ["brown eyes", "detailed iris"], "hair": ["(light brown hair:1.1)", "long hair", "(straight bangs:1.25)"], "accesories": {"head": ["(silver hoop earrings:1.1)"], "neck": ["(black velvet choker:1.1)"]}, "beauty mark": ["(single mole under right eye:1.35)"]}, "config_paths": {"mod_config": "configs/personas/Lotta/workflows/templates/workflow_args.json", "scene_conf": "configs/personas/Lotta/assets/scene.json", "camera_conf": "configs/personas/Lotta/assets/camera.json", "wardrobe_conf": "configs/personas/Lotta/assets/wardrobe.json", "expression_conf": "configs/personas/Lotta/assets/expressions.json", "environment_conf": "configs/personas/Lotta/assets/environments.json"}, "target_model": "PonyRealism", "negative_base": "(two people:1.45), (multiple people:1.4), (2people:1.45), (plastic skin:1.2), plastic_texture, lens_flare_artifact, (anime:1.3), 3d, render, blurry, lowres, bad hands, error, blurry", "negative_face": "(grimace:1.2), (bad teeth:1.3), (crooked teeth:1.2), (scary smile:1.2), (multiple moles:1.4), (freckles:1.4)", "negative_logic": {"items": [{"id": "neg_base_defense", "tags": "(plastic texture:1.2), (cartoon:1.3), (oversharpen:1.2), (unnatural skin tone:1.3), (lens artifact:1.2), (bad anatomy:1.3), (extra fingers:1.4), (deformed limbs:1.3)", "max_lv": 5, "min_lv": 1, "weight": 1.0, "description": "全レベル共通：低品質・写実性を損なうアーティファクトを排除"}, {"id": "neg_lv3_borderline", "tags": "(explicit nipples:1.0), (explicit genitalia:1.0), (graphic sexual content:1.2)", "max_lv": 3, "min_lv": 1, "weight": 1.2, "description": "Lv1-3専用：写実表現の範囲で過度な露出や器官の直接描写を防ぐ"}, {"id": "neg_lv4_reinforced", "tags": "(penis:1.1), (dick:1.1), (cock:1.1), (unrealistic proportions:1.2)", "max_lv": 5, "min_lv": 4, "weight": 1.0, "description": "Lv4以上：画風崩壊を招く過度な表現を拒否"}]}, "base_score_tags": "score_9, score_8_up, score_7_up", "base_identity_tags": "1woman, adult, (korean or taiwanese ethnicity:1.2)", "negative_holy_grail": "(worst quality, low quality:1.4), bad anatomy, text, logo, watermark, oversaturated colors", "innerwear_thresholds": {"1": 0, "2": 20, "3": 85, "4": 100}}',2,TIMESTAMP '2026-07-12 10:39:28.133')
  , ('{400c1bc9-5c4e-45b2-8d59-9d9c730da4cf}','{39eff062-1d05-41a0-9777-ca949b445844}','Aoi','https://example.com/aoi.png','{"name": "Aoi", "rating": {"safe": "rating_safe", "explicit": "rating_explicit", "questionable": "rating_questionable"}, "base_style": "1980s retro anime style, Haruhiko Mikimoto style, cinematic grain, shakerato", "body_parts": {"eyes": ["blue eyes"], "hair": ["(pure black hair:1.3)", "long hair"], "accesories": {"head": ["(pink headphones worn on head:1.3)"], "neck": ["(leather choker:1.2)"]}}, "config_paths": {"mod_config": "configs/personas/Aoi/workflows/templates/workflow_args.json", "scene_conf": "configs/personas/Aoi/assets/scene.json", "camera_conf": "configs/personas/Aoi/assets/camera.json", "wardrobe_conf": "configs/personas/Aoi/assets/wardrobe.json", "expression_conf": "configs/personas/Aoi/assets/expressions.json", "environment_conf": "configs/personas/Aoi/assets/environments.json"}, "target_model": "ebaraPony", "negative_base": "(headphones_around_neck:1.2), (headphones_on_shoulders:1.2), (sunglasses:1.1), (goggles:1.1), (eyewear on head:1.1), (visor:1.1), (head-mounted display:1.2), (glasses:1.1), (anime:1.3), 3d, render, blurry, lowres, bad hands, error, blurry", "negative_face": "(grimace:1.2), (bad_teeth:1.3), (crooked_teeth:1.2), (scary_smile:1.2)", "negative_logic": {"items": [{"id": "neg_base_defense", "tags": "(plastic_texture:1.1)", "max_lv": 5, "min_lv": 1, "weight": 1.0, "description": "全レベル共通：現代風と低品質を排除する基本防壁"}, {"id": "neg_lv3_borderline", "tags": "(nipples:1.0), (pussy:1.0), (extra fingers:1.2), (other''s hand:1.4), (hand on shoulder:1.1), (hug:1.1), (interacting:1.1), (2multiple girls:1.1), (group:1.2)", "max_lv": 3, "min_lv": 3, "weight": 1.2, "description": "Lv1-3専用：下着は許可するが、乳首・性器・直接的露出を厳禁する防壁"}, {"id": "neg_lv4_reinforced", "tags": "(penis:1.1), (dick:1.1), (cock:1.1)", "max_lv": 4, "min_lv": 4, "weight": 1.0, "description": "Lv4専用：過激なタグによる画風崩壊と、下品すぎる漫符を徹底拒絶"}]}, "base_score_tags": "(score_9, score_8_up:1.2)", "base_identity_tags": "1girl", "negative_holy_grail": "score_4, score_5, score_6, low quality, bad anatomy, text, watermark", "innerwear_thresholds": {"1": 0, "2": 20, "3": 85, "4": 100}}',1,TIMESTAMP '2026-07-12 10:39:28.133');

-- bot_profiles
INSERT INTO personyx.bot_profiles (group_id, name, active_persona_id, is_active)
VALUES 
  (1, 'Aoi', '400c1bc9-5c4e-45b2-8d59-9d9c730da4cf', TRUE),
  (2, 'Lotta', '1166e3bb-6824-4dd0-945c-80eec3721810', TRUE);

--  user_bot_profiles
INSERT INTO personyx.user_bot_profiles (user_id, group_id, bot_profile_id, is_active)
VALUES
  ('39eff062-1d05-41a0-9777-ca949b445844', 1, 4, TRUE);


