"""bot_profile_groupsテーブル追加。関連するテーブルにリレーション追加

Revision ID: 12319eb91031
Revises: e094f032d985
Create Date: 2026-07-12 22:26:58.885487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12319eb91031'
down_revision: Union[str, Sequence[str], None] = 'e094f032d985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_profile_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['personyx.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_bot_profile_groups_created_at'), 'bot_profile_groups', ['created_at'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_bot_profile_groups_is_active'), 'bot_profile_groups', ['is_active'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_bot_profile_groups_user_id'), 'bot_profile_groups', ['user_id'], unique=False, schema='personyx')
    op.add_column('bot_profiles', sa.Column('group_id', sa.Integer(), nullable=False))
    op.drop_constraint('bot_profiles_name_key', 'bot_profiles', type_='unique')
    op.create_index(op.f('ix_personyx_bot_profiles_group_id'), 'bot_profiles', ['group_id'], unique=False, schema='personyx')
    op.create_unique_constraint('uq_bot_profiles_group_name', 'bot_profiles', ['group_id', 'name'], schema='personyx')
    op.drop_constraint('bot_profiles_active_persona_id_fkey', 'bot_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.create_foreign_key(None, 'bot_profiles', 'personas', ['active_persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.drop_constraint('images_persona_id_fkey', 'images', type_='foreignkey')
    op.drop_constraint('images_user_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'images', 'personas', ['persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.drop_constraint('personas_user_id_fkey', 'personas', type_='foreignkey')
    op.drop_constraint('personas_workflow_id_fkey', 'personas', type_='foreignkey')
    op.create_foreign_key(None, 'personas', 'workflows', ['workflow_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'personas', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='RESTRICT')
    op.drop_constraint('user_accounts_user_id_fkey', 'user_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'user_accounts', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.add_column('user_bot_profiles', sa.Column('group_id', sa.Integer(), nullable=False))
    op.drop_constraint('uq_user_bot_profiles_user_active', 'user_bot_profiles', type_='unique')
    op.create_index(op.f('ix_personyx_user_bot_profiles_group_id'), 'user_bot_profiles', ['group_id'], unique=False, schema='personyx')
    op.drop_constraint('user_bot_profiles_user_id_fkey', 'user_bot_profiles', type_='foreignkey')
    op.drop_constraint('user_bot_profiles_bot_profile_id_fkey', 'user_bot_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_bot_profiles', 'bot_profiles', ['bot_profile_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_bot_profiles', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.create_foreign_key('user_bot_profiles_bot_profile_id_fkey', 'user_bot_profiles', 'bot_profiles', ['bot_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_bot_profiles_user_id_fkey', 'user_bot_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_personyx_user_bot_profiles_group_id'), table_name='user_bot_profiles', schema='personyx')
    op.create_unique_constraint('uq_user_bot_profiles_user_active', 'user_bot_profiles', ['user_id', 'is_active'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_bot_profiles', 'group_id')
    op.drop_constraint(None, 'user_accounts', schema='personyx', type_='foreignkey')
    op.create_foreign_key('user_accounts_user_id_fkey', 'user_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'personas', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'personas', schema='personyx', type_='foreignkey')
    op.create_foreign_key('personas_workflow_id_fkey', 'personas', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('personas_user_id_fkey', 'personas', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.create_foreign_key('images_user_id_fkey', 'images', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('images_persona_id_fkey', 'images', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'bot_profiles', schema='personyx', type_='foreignkey')
    op.create_foreign_key('bot_profiles_active_persona_id_fkey', 'bot_profiles', 'personas', ['active_persona_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_bot_profiles_group_name', 'bot_profiles', schema='personyx', type_='unique')
    op.drop_index(op.f('ix_personyx_bot_profiles_group_id'), table_name='bot_profiles', schema='personyx')
    op.create_unique_constraint('bot_profiles_name_key', 'bot_profiles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('bot_profiles', 'group_id')
    op.drop_index(op.f('ix_personyx_bot_profile_groups_user_id'), table_name='bot_profile_groups', schema='personyx')
    op.drop_index(op.f('ix_personyx_bot_profile_groups_is_active'), table_name='bot_profile_groups', schema='personyx')
    op.drop_index(op.f('ix_personyx_bot_profile_groups_created_at'), table_name='bot_profile_groups', schema='personyx')
    op.drop_table('bot_profile_groups', schema='personyx')
    # ### end Alembic commands ###
