"""add column to images

Revision ID: 44721452cb61
Revises: b7b6d0d5fa15
Create Date: 2026-05-21 12:22:37.416595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44721452cb61'
down_revision: Union[str, Sequence[str], None] = 'b7b6d0d5fa15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('generated_by_user', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'generated_by_user')
    # ### end Alembic commands ###
