"""user_bot_profilesのリレーションにおけるback_populatesをgroupsに変更

Revision ID: 87c803ba0631
Revises: af1df0fb68dd
Create Date: 2026-07-17 07:24:10.986801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c803ba0631'
down_revision: Union[str, Sequence[str], None] = 'af1df0fb68dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bot_profile_groups_user_id_fkey', 'bot_profile_groups', type_='foreignkey')
    op.create_foreign_key(None, 'bot_profile_groups', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.drop_constraint('bot_profiles_group_id_fkey', 'bot_profiles', type_='foreignkey')
    op.drop_constraint('bot_profiles_active_persona_id_fkey', 'bot_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.create_foreign_key(None, 'bot_profiles', 'personas', ['active_persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.drop_constraint('images_persona_id_fkey', 'images', type_='foreignkey')
    op.drop_constraint('images_user_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'images', 'personas', ['persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.drop_constraint('personas_user_id_fkey', 'personas', type_='foreignkey')
    op.drop_constraint('personas_workflow_id_fkey', 'personas', type_='foreignkey')
    op.create_foreign_key(None, 'personas', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='RESTRICT')
    op.create_foreign_key(None, 'personas', 'workflows', ['workflow_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.drop_constraint('user_accounts_user_id_fkey', 'user_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'user_accounts', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.drop_constraint('user_bot_profiles_group_id_fkey', 'user_bot_profiles', type_='foreignkey')
    op.drop_constraint('user_bot_profiles_bot_profile_id_fkey', 'user_bot_profiles', type_='foreignkey')
    op.drop_constraint('user_bot_profiles_user_id_fkey', 'user_bot_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_bot_profiles', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_bot_profiles', 'bot_profiles', ['bot_profile_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.create_foreign_key('user_bot_profiles_user_id_fkey', 'user_bot_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_bot_profiles_bot_profile_id_fkey', 'user_bot_profiles', 'bot_profiles', ['bot_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_bot_profiles_group_id_fkey', 'user_bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_accounts', schema='personyx', type_='foreignkey')
    op.create_foreign_key('user_accounts_user_id_fkey', 'user_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'personas', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'personas', schema='personyx', type_='foreignkey')
    op.create_foreign_key('personas_workflow_id_fkey', 'personas', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('personas_user_id_fkey', 'personas', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.create_foreign_key('images_user_id_fkey', 'images', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('images_persona_id_fkey', 'images', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'bot_profiles', schema='personyx', type_='foreignkey')
    op.create_foreign_key('bot_profiles_active_persona_id_fkey', 'bot_profiles', 'personas', ['active_persona_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('bot_profiles_group_id_fkey', 'bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bot_profile_groups', schema='personyx', type_='foreignkey')
    op.create_foreign_key('bot_profile_groups_user_id_fkey', 'bot_profile_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
