"""Add OAuth2 support

Revision ID: af884ee64c0f
Revises: 44721452cb61
Create Date: 2026-05-29 13:35:32.905343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af884ee64c0f'
down_revision: Union[str, Sequence[str], None] = '44721452cb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_users_created_at'), 'users', ['created_at'], unique=False, schema='personyx')
    op.create_table('user_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['personyx.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user_id'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_user_accounts_provider_user_id'), 'user_accounts', ['provider_user_id'], unique=False, schema='personyx')
    op.add_column('images', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.drop_column('images', 'generated_by_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('generated_by_user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.drop_column('images', 'user_id')
    op.drop_index(op.f('ix_personyx_user_accounts_provider_user_id'), table_name='user_accounts', schema='personyx')
    op.drop_table('user_accounts', schema='personyx')
    op.drop_index(op.f('ix_personyx_users_created_at'), table_name='users', schema='personyx')
    op.drop_table('users', schema='personyx')
    # ### end Alembic commands ###
