"""init_tables

Revision ID: b7b6d0d5fa15
Revises: 
Create Date: 2026-05-01 13:39:35.914530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7b6d0d5fa15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('rating_level', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.String(length=50), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('prompt_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_images_created_at'), 'images', ['created_at'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_images_is_favorite'), 'images', ['is_favorite'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_images_rating_level'), 'images', ['rating_level'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_images_scene_id'), 'images', ['scene_id'], unique=False, schema='personyx')
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='personyx'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs', schema='personyx')
    op.drop_index(op.f('ix_personyx_images_scene_id'), table_name='images', schema='personyx')
    op.drop_index(op.f('ix_personyx_images_rating_level'), table_name='images', schema='personyx')
    op.drop_index(op.f('ix_personyx_images_is_favorite'), table_name='images', schema='personyx')
    op.drop_index(op.f('ix_personyx_images_created_at'), table_name='images', schema='personyx')
    op.drop_table('images', schema='personyx')
    # ### end Alembic commands ###
