"""personasテーブル、workflowsテーブルを追加。imagesテーブルにpersona_idを追加

Revision ID: c74b7c0e1ee8
Revises: af884ee64c0f
Create Date: 2026-07-11 14:57:43.452942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c74b7c0e1ee8'
down_revision: Union[str, Sequence[str], None] = 'af884ee64c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_workflows_created_at'), 'workflows', ['created_at'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_workflows_name'), 'workflows', ['name'], unique=False, schema='personyx')
    op.create_table('personas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('persona_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['personyx.users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['personyx.workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_personas_created_at'), 'personas', ['created_at'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_personas_name'), 'personas', ['name'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_personas_workflow_id'), 'personas', ['workflow_id'], unique=False, schema='personyx')
    op.add_column('images', sa.Column('persona_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_personyx_images_persona_id'), 'images', ['persona_id'], unique=False, schema='personyx')
    op.drop_constraint('images_user_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'images', 'personas', ['persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.drop_constraint('user_accounts_user_id_fkey', 'user_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'user_accounts', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', schema='personyx', type_='foreignkey')
    op.create_foreign_key('user_accounts_user_id_fkey', 'user_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.create_foreign_key('images_user_id_fkey', 'images', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_personyx_images_persona_id'), table_name='images', schema='personyx')
    op.drop_column('images', 'persona_id')
    op.drop_index(op.f('ix_personyx_personas_workflow_id'), table_name='personas', schema='personyx')
    op.drop_index(op.f('ix_personyx_personas_name'), table_name='personas', schema='personyx')
    op.drop_index(op.f('ix_personyx_personas_created_at'), table_name='personas', schema='personyx')
    op.drop_table('personas', schema='personyx')
    op.drop_index(op.f('ix_personyx_workflows_name'), table_name='workflows', schema='personyx')
    op.drop_index(op.f('ix_personyx_workflows_created_at'), table_name='workflows', schema='personyx')
    op.drop_table('workflows', schema='personyx')
    # ### end Alembic commands ###
