"""ユニークインデックス追加

Revision ID: d160785c37d2
Revises: f5cac561df6e
Create Date: 2026-09-25 07:21:58.452742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd160785c37d2'
down_revision: Union[str, Sequence[str], None] = 'f5cac561df6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bot_profile_groups_user_id_fkey', 'bot_profile_groups', type_='foreignkey')
    op.create_foreign_key(None, 'bot_profile_groups', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.drop_constraint('bot_profiles_active_persona_id_fkey', 'bot_profiles', type_='foreignkey')
    op.drop_constraint('bot_profiles_group_id_fkey', 'bot_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'bot_profiles', 'personas', ['active_persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.drop_constraint('images_persona_id_fkey', 'images', type_='foreignkey')
    op.drop_constraint('images_user_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'personas', ['persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.drop_constraint('persona_asset_files_persona_id_fkey', 'persona_asset_files', type_='foreignkey')
    op.create_foreign_key(None, 'persona_asset_files', 'personas', ['persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.drop_constraint('persona_assets_persona_id_fkey', 'persona_assets', type_='foreignkey')
    op.create_foreign_key(None, 'persona_assets', 'personas', ['persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.drop_constraint('persona_character_specs_persona_id_fkey', 'persona_character_specs', type_='foreignkey')
    op.create_foreign_key(None, 'persona_character_specs', 'personas', ['persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.drop_constraint('persona_workflow_overrides_persona_id_fkey', 'persona_workflow_overrides', type_='foreignkey')
    op.create_foreign_key(None, 'persona_workflow_overrides', 'personas', ['persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.drop_constraint('personas_user_id_fkey', 'personas', type_='foreignkey')
    op.drop_constraint('personas_workflow_id_fkey', 'personas', type_='foreignkey')
    op.create_foreign_key(None, 'personas', 'workflows', ['workflow_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'personas', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='RESTRICT')
    op.drop_constraint('user_accounts_user_id_fkey', 'user_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'user_accounts', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.create_index('uq_user_bot_profiles_user_active', 'user_bot_profiles', ['user_id'], unique=True, schema='personyx', postgresql_where=sa.text('is_active = true'))
    op.drop_constraint('user_bot_profiles_bot_profile_id_fkey', 'user_bot_profiles', type_='foreignkey')
    op.drop_constraint('user_bot_profiles_group_id_fkey', 'user_bot_profiles', type_='foreignkey')
    op.drop_constraint('user_bot_profiles_user_id_fkey', 'user_bot_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_bot_profiles', 'bot_profiles', ['bot_profile_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_bot_profiles', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.create_foreign_key('user_bot_profiles_user_id_fkey', 'user_bot_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_bot_profiles_group_id_fkey', 'user_bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_bot_profiles_bot_profile_id_fkey', 'user_bot_profiles', 'bot_profiles', ['bot_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_user_bot_profiles_user_active', table_name='user_bot_profiles', schema='personyx', postgresql_where=sa.text('is_active = true'))
    op.drop_constraint(None, 'user_accounts', schema='personyx', type_='foreignkey')
    op.create_foreign_key('user_accounts_user_id_fkey', 'user_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'personas', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'personas', schema='personyx', type_='foreignkey')
    op.create_foreign_key('personas_workflow_id_fkey', 'personas', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('personas_user_id_fkey', 'personas', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'persona_workflow_overrides', schema='personyx', type_='foreignkey')
    op.create_foreign_key('persona_workflow_overrides_persona_id_fkey', 'persona_workflow_overrides', 'personas', ['persona_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'persona_character_specs', schema='personyx', type_='foreignkey')
    op.create_foreign_key('persona_character_specs_persona_id_fkey', 'persona_character_specs', 'personas', ['persona_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'persona_assets', schema='personyx', type_='foreignkey')
    op.create_foreign_key('persona_assets_persona_id_fkey', 'persona_assets', 'personas', ['persona_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'persona_asset_files', schema='personyx', type_='foreignkey')
    op.create_foreign_key('persona_asset_files_persona_id_fkey', 'persona_asset_files', 'personas', ['persona_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.create_foreign_key('images_user_id_fkey', 'images', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('images_persona_id_fkey', 'images', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'bot_profiles', schema='personyx', type_='foreignkey')
    op.create_foreign_key('bot_profiles_group_id_fkey', 'bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bot_profiles_active_persona_id_fkey', 'bot_profiles', 'personas', ['active_persona_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'bot_profile_groups', schema='personyx', type_='foreignkey')
    op.create_foreign_key('bot_profile_groups_user_id_fkey', 'bot_profile_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
