"""bot_profilesテーブル、user_bot_profilesテーブル追加。関連するテーブルにリレーション追加

Revision ID: e094f032d985
Revises: c74b7c0e1ee8
Create Date: 2026-07-12 10:22:28.064535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e094f032d985'
down_revision: Union[str, Sequence[str], None] = 'c74b7c0e1ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active_persona_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['active_persona_id'], ['personyx.personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_bot_profiles_active_persona_id'), 'bot_profiles', ['active_persona_id'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_bot_profiles_created_at'), 'bot_profiles', ['created_at'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_bot_profiles_is_active'), 'bot_profiles', ['is_active'], unique=False, schema='personyx')
    op.create_table('user_bot_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bot_profile_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_profile_id'], ['personyx.bot_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['personyx.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bot_profile_id', name='uq_user_bot_profiles_user_profile'),
    sa.UniqueConstraint('user_id', 'is_active', name='uq_user_bot_profiles_user_active'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_user_bot_profiles_bot_profile_id'), 'user_bot_profiles', ['bot_profile_id'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_user_bot_profiles_created_at'), 'user_bot_profiles', ['created_at'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_user_bot_profiles_is_active'), 'user_bot_profiles', ['is_active'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_user_bot_profiles_user_id'), 'user_bot_profiles', ['user_id'], unique=False, schema='personyx')
    op.drop_constraint('images_persona_id_fkey', 'images', type_='foreignkey')
    op.drop_constraint('images_user_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'images', 'personas', ['persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.drop_constraint('personas_user_id_fkey', 'personas', type_='foreignkey')
    op.drop_constraint('personas_workflow_id_fkey', 'personas', type_='foreignkey')
    op.create_foreign_key(None, 'personas', 'workflows', ['workflow_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'personas', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='RESTRICT')
    op.drop_constraint('user_accounts_user_id_fkey', 'user_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'user_accounts', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', schema='personyx', type_='foreignkey')
    op.create_foreign_key('user_accounts_user_id_fkey', 'user_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'personas', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'personas', schema='personyx', type_='foreignkey')
    op.create_foreign_key('personas_workflow_id_fkey', 'personas', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('personas_user_id_fkey', 'personas', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.create_foreign_key('images_user_id_fkey', 'images', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('images_persona_id_fkey', 'images', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_personyx_user_bot_profiles_user_id'), table_name='user_bot_profiles', schema='personyx')
    op.drop_index(op.f('ix_personyx_user_bot_profiles_is_active'), table_name='user_bot_profiles', schema='personyx')
    op.drop_index(op.f('ix_personyx_user_bot_profiles_created_at'), table_name='user_bot_profiles', schema='personyx')
    op.drop_index(op.f('ix_personyx_user_bot_profiles_bot_profile_id'), table_name='user_bot_profiles', schema='personyx')
    op.drop_table('user_bot_profiles', schema='personyx')
    op.drop_index(op.f('ix_personyx_bot_profiles_is_active'), table_name='bot_profiles', schema='personyx')
    op.drop_index(op.f('ix_personyx_bot_profiles_created_at'), table_name='bot_profiles', schema='personyx')
    op.drop_index(op.f('ix_personyx_bot_profiles_active_persona_id'), table_name='bot_profiles', schema='personyx')
    op.drop_table('bot_profiles', schema='personyx')
    # ### end Alembic commands ###
