"""ペルソナ設定をDBへ移管する

Revision ID: f5cac561df6e
Revises: 391407443eca
Create Date: 2026-09-21 14:33:43.616736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5cac561df6e'
down_revision: Union[str, Sequence[str], None] = '391407443eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_asset_files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_key', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personyx.personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'asset_type', 'asset_key', name='uq_persona_asset_file_key'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_persona_asset_files_asset_key'), 'persona_asset_files', ['asset_key'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_persona_asset_files_asset_type'), 'persona_asset_files', ['asset_type'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_persona_asset_files_created_at'), 'persona_asset_files', ['created_at'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_persona_asset_files_persona_id'), 'persona_asset_files', ['persona_id'], unique=False, schema='personyx')
    op.create_table('persona_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_key', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personyx.personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'asset_type', 'asset_key', name='uq_persona_asset_key'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_persona_assets_asset_key'), 'persona_assets', ['asset_key'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_persona_assets_asset_type'), 'persona_assets', ['asset_type'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_persona_assets_created_at'), 'persona_assets', ['created_at'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_persona_assets_persona_id'), 'persona_assets', ['persona_id'], unique=False, schema='personyx')
    op.create_table('persona_character_specs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_model', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personyx.personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_persona_character_specs_created_at'), 'persona_character_specs', ['created_at'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_persona_character_specs_persona_id'), 'persona_character_specs', ['persona_id'], unique=False, schema='personyx')
    op.create_index('uq_persona_character_spec_default', 'persona_character_specs', ['persona_id'], unique=True, schema='personyx', postgresql_where=sa.text('is_default = true'))
    op.create_table('persona_workflow_overrides',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('workflow_kind', sa.String(length=50), nullable=False),
    sa.Column('workflow_name', sa.String(length=255), nullable=False),
    sa.Column('workflow_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personyx.personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='personyx'
    )
    op.create_index(op.f('ix_personyx_persona_workflow_overrides_created_at'), 'persona_workflow_overrides', ['created_at'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_persona_workflow_overrides_persona_id'), 'persona_workflow_overrides', ['persona_id'], unique=False, schema='personyx')
    op.create_index(op.f('ix_personyx_persona_workflow_overrides_workflow_kind'), 'persona_workflow_overrides', ['workflow_kind'], unique=False, schema='personyx')
    op.drop_constraint('bot_profile_groups_user_id_fkey', 'bot_profile_groups', type_='foreignkey')
    op.create_foreign_key(None, 'bot_profile_groups', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.drop_constraint('bot_profiles_active_persona_id_fkey', 'bot_profiles', type_='foreignkey')
    op.drop_constraint('bot_profiles_group_id_fkey', 'bot_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'bot_profiles', 'personas', ['active_persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.drop_constraint('images_persona_id_fkey', 'images', type_='foreignkey')
    op.drop_constraint('images_user_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'personas', ['persona_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.drop_constraint('personas_user_id_fkey', 'personas', type_='foreignkey')
    op.drop_constraint('personas_workflow_id_fkey', 'personas', type_='foreignkey')
    op.create_foreign_key(None, 'personas', 'workflows', ['workflow_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='SET NULL')
    op.create_foreign_key(None, 'personas', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='RESTRICT')
    op.drop_constraint('user_accounts_user_id_fkey', 'user_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'user_accounts', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.drop_constraint('user_bot_profiles_user_id_fkey', 'user_bot_profiles', type_='foreignkey')
    op.drop_constraint('user_bot_profiles_bot_profile_id_fkey', 'user_bot_profiles', type_='foreignkey')
    op.drop_constraint('user_bot_profiles_group_id_fkey', 'user_bot_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_bot_profiles', 'users', ['user_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_bot_profiles', 'bot_profiles', ['bot_profile_id'], ['id'], source_schema='personyx', referent_schema='personyx', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'user_bot_profiles', schema='personyx', type_='foreignkey')
    op.create_foreign_key('user_bot_profiles_group_id_fkey', 'user_bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_bot_profiles_bot_profile_id_fkey', 'user_bot_profiles', 'bot_profiles', ['bot_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_bot_profiles_user_id_fkey', 'user_bot_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_accounts', schema='personyx', type_='foreignkey')
    op.create_foreign_key('user_accounts_user_id_fkey', 'user_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'personas', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'personas', schema='personyx', type_='foreignkey')
    op.create_foreign_key('personas_workflow_id_fkey', 'personas', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('personas_user_id_fkey', 'personas', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'images', schema='personyx', type_='foreignkey')
    op.create_foreign_key('images_user_id_fkey', 'images', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('images_persona_id_fkey', 'images', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'bot_profiles', schema='personyx', type_='foreignkey')
    op.drop_constraint(None, 'bot_profiles', schema='personyx', type_='foreignkey')
    op.create_foreign_key('bot_profiles_group_id_fkey', 'bot_profiles', 'bot_profile_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bot_profiles_active_persona_id_fkey', 'bot_profiles', 'personas', ['active_persona_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'bot_profile_groups', schema='personyx', type_='foreignkey')
    op.create_foreign_key('bot_profile_groups_user_id_fkey', 'bot_profile_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_personyx_persona_workflow_overrides_workflow_kind'), table_name='persona_workflow_overrides', schema='personyx')
    op.drop_index(op.f('ix_personyx_persona_workflow_overrides_persona_id'), table_name='persona_workflow_overrides', schema='personyx')
    op.drop_index(op.f('ix_personyx_persona_workflow_overrides_created_at'), table_name='persona_workflow_overrides', schema='personyx')
    op.drop_table('persona_workflow_overrides', schema='personyx')
    op.drop_index('uq_persona_character_spec_default', table_name='persona_character_specs', schema='personyx', postgresql_where=sa.text('is_default = true'))
    op.drop_index(op.f('ix_personyx_persona_character_specs_persona_id'), table_name='persona_character_specs', schema='personyx')
    op.drop_index(op.f('ix_personyx_persona_character_specs_created_at'), table_name='persona_character_specs', schema='personyx')
    op.drop_table('persona_character_specs', schema='personyx')
    op.drop_index(op.f('ix_personyx_persona_assets_persona_id'), table_name='persona_assets', schema='personyx')
    op.drop_index(op.f('ix_personyx_persona_assets_created_at'), table_name='persona_assets', schema='personyx')
    op.drop_index(op.f('ix_personyx_persona_assets_asset_type'), table_name='persona_assets', schema='personyx')
    op.drop_index(op.f('ix_personyx_persona_assets_asset_key'), table_name='persona_assets', schema='personyx')
    op.drop_table('persona_assets', schema='personyx')
    op.drop_index(op.f('ix_personyx_persona_asset_files_persona_id'), table_name='persona_asset_files', schema='personyx')
    op.drop_index(op.f('ix_personyx_persona_asset_files_created_at'), table_name='persona_asset_files', schema='personyx')
    op.drop_index(op.f('ix_personyx_persona_asset_files_asset_type'), table_name='persona_asset_files', schema='personyx')
    op.drop_index(op.f('ix_personyx_persona_asset_files_asset_key'), table_name='persona_asset_files', schema='personyx')
    op.drop_table('persona_asset_files', schema='personyx')
    # ### end Alembic commands ###
